// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekdizcuhtpxlxyodpdmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrZGl6Y3VodHB4bHh5b2RwZG1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NzYxNDEsImV4cCI6MjA1NzU1MjE0MX0.aZdDvthN1wKkF7GOBI9ikkJ5MBnu2BAa3FBNYW3yO5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);